### PR TITLE
Share Guard code across repositories

### PR DESCRIPTION
**Pull request by antonfirsov**
Currently Guard and `DebugGuard` is being shared as an internal of `SixLabors.Core`. This could lead to compatibility issues.

I'm suggesting to share the code the code instead with the help of already existing "Standards" submodule. The classes are tested within the bounds of the SixLabors.Core repository.

### Parallel PR-s to apply the change in across repositories
- SixLabors/Core#33
- SixLabors/Fonts#113
- SixLabors/Shapes#69
- TODO: open PR in SixLabors/ImageSharp when the rest has been merged

### CODE REVIEW

**Comment by antonfirsov** [comment]
@JimBobSquarePants that would mean introducing yet another infrastructure element raising where/how +maintenance questions. Submodules are already in place for our stuff, and looking simpler to me (no need to publish on myget etc.).

**Comment by antonfirsov** [comment]
If we find it's worth the efforts, we can repackage it later anytime. For now I just want to get rid of those dangerous dependencies for the next beta.

**Comment by JimBobSquarePants** [comment]
Those projects don’t get deployed, only their source is shared to the consuming projects so package management is not a factor. We can also enforce standards rules on the shared code.

I’d much rather introduce a new submodule here anyway rather than pollute standards, or replace standards with something more aptly named if we are to use it as a general store.

**Comment by antonfirsov** [comment]
@JimBobSquarePants I've renamed the repository, and [changed `README.md`](https://github.com/SixLabors/SharedInfrastructure/blob/73b6f4c24236fe9cc80e688dfcc0f58f441d87a7/README.md) according to it's new purpose.

Now it needs an extensive review together SixLabors/Core#33, before so we can do the rest of the work. I'll change and finalize the remaining PR-s, as soon as this one is merged.

**Comment by JimBobSquarePants** [comment]
@antonfirsov I've just pushed an update that uses the most up-to-date `.editorconfig` (plus VS 16.2.2 fix) and `.gitattributes` so we can share them across our repos also.

Additionally I've reordered the `SixLabors.ruleset` config for readability and added a new  `SixLabors.Tests.ruleset` that contains a slimmed down ruleset more suitable for our unit tests. 

The readme has been updated to reflect those changes.

I still think we should use shared projects in the future over standalone `.cs` files but that can wait for future discussion.

**Comment by antonfirsov** [comment]
To me it looks like the "Shared project" is a concept predating the new [SDK-style](https://github.com/microsoft/MSBuildSdks#what-are-msbuild-sdks) msbuild projects, and could be replaced by a simple `<Import ... />` nowadays.

We should investigate these practices when we share `.props` / `.targets` across our repositories.

**Pull request merged**
