### PR TITLE
Define SUPPORTS_BITOPERATIONS

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/SharedInfrastructure/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Needs netcoreapp>3.0 which means we should target netstandard2.1 or netcoreapp3.1 (&net5)-

https://apisof.net/catalog/1893e3da-8739-60f0-e476-12e837a214af
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

### CODE REVIEW

**Comment by br3aker** [comment]
There's an error in this PR: `SUPPORTS_BITOPERATIONS` should **not** be defined on netcore 2.1. `BitOperations` class is supported on >=netcore3.0: https://apisof.net/catalog/03b296af-2fee-f779-4d14-eed4c227464f.

**Comment by antonfirsov** [comment]
Yeah, I did it in rush, and messed up following a stupid logic implying netstandard21 from netcoreapp30.

**Comment by JimBobSquarePants** [comment]
Whoops! I read the table and changes and didn’t follow the links. Easy to fix

**Comment by JimBobSquarePants** [comment]
Fixed with #19

**Pull request merged**
