### PR TITLE
Improved Guard APIs codegen

### PR DESCRIPTION
**Pull request by Sergio0694**
The JIT assumes that forward branches are always taken, and with the custom `ThrowHelper` methods used in the `Guard` APIs having the `[MethodImpl]` attributes, it couldn't see that they were always throwing, so the resulting codegen was not optimal. I've inverted all the conditions so that the forward branch is the likely one (the one that doesn't fault). This allowes the JIT to properly optimize the codegen in methods using the `Guard` APIs, eg. by only using jumps for the faulting paths and placing them further down in the code, with the likely branch not having to jump instead. These are the same changes done in the `Microsoft.Toolkit.Diagnostics.Guard` class, see https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3323.

**NOTE:** @JimBobSquarePants not sure how to generate that `.tt.bak` file, could you tell me what steps I should do here?

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
>not sure how to generate that .tt.bak file, could you tell me what steps I should do here?

Easy peasy... I simply renamed the `.tt` file after I'd generated the classes from it! 😄

**Comment by Sergio0694** [comment]
Oh...
Not sure why, I saw that `.bak` extension and just assumed it must've had to do with some custom build script or something 🤣

Well that worked, PR should be good to go now, thanks! 🎉

**Comment by JimBobSquarePants** [comment]
I'm gonna see if I can get CI up and running for this PR to improve test visibility.

**Comment by JimBobSquarePants** [comment]
@MarcoRossignoli I hate to do this but I can't figure out why the code coverage reports here are empty?

Would you be able to take a quick look when you are able, no rush! Thanks!

**Comment by JimBobSquarePants** [comment]
@Sergio0694 Our code coverage is appalling. I'd like to do some work on that before merging.

**Comment by Sergio0694** [comment]
@JimBobSquarePants Are we missing tests for `ThrowHelper` or for `Guard` too?
I could port/adapt some of those I have in the toolkit (see [here](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/UnitTests/UnitTests.Shared/Diagnostics))?

Also, side question - do we need another PR to update the submodule reference for ImageSharp after this is merged?
Not super familiar with submodules myself so not sure if there's some automation there or something 😅

**Comment by JimBobSquarePants** [comment]
@Sergio0694  Yeah we need tests for everything. You can see the coverage here.

https://codecov.io/gh/SixLabors/SharedInfrastructure/pull/12/tree

Once we've finished, yep it's a new PR for each consuming repo. Hopefully this is the last change we'll see for a while.

**Comment by MarcoRossignoli** [comment]
Hi guys!

> Scratch that, figured it out! Because we are including the shared project directly into the test project I had to configure the .runsettings file in the following manner.

Yep test project is not included in coverage by default

Let me know if need further assistance

**Comment by JimBobSquarePants** [comment]
@MarcoRossignoli Thanks mate! Once I'd remembered how my project worked it was dead easy. Love how simple the configuration options are!

**Review by JimBobSquarePants — APPROVED** [review]

**Pull request merged**
